baseurl = "http://www.cwestb.com"
languageCode = "en-us"
title = "Sally Hagy-Boyer's Blog"
disqusShortname = "shbartist"
[taxonomies]
   author = "authors"
   series = "series"
   tag = "tags"
   category = "categories"
